name: ProfileSwitcher
version: '1.0-SNAPSHOT'
main: com.github.bobryanskiy.profileSwitcher.ProfileSwitcher
api-version: '1.21.4'

permissions:
  permission.node:
    description: "This is a permission node"
    default: op
    children:
      permission.node.child: true
  another.permission.node:
    description: "This is another permission node"
    default: not op

commands:
  switchme:
    description: "Command to switch profile"
    usage: "/switchme"