name: ProfileSwitcher
version: '1.0-SNAPSHOT'
main: com.github.bobryanskiy.profileSwitcher.ProfileSwitcher
api-version: '1.21.4'

commands:
  switchme:
    description: "Command to switch profile"
    usage: "/switchme"
    permission: op